config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#home'
  get '/dashboard' => 'dashboard#dashboard'
  get '/login' => 'login#login'
  get '/signup' => 'signup#signup'
  # get '/courses' => 'courses#courses'
  get '/teachers' => 'teachers#teachers'
  get '/students' => 'students#students'
  get '/about' => 'about#about'
  get '/contact' => 'contact#contact'
  
 
  get '/course/:id' => 'courses#destroy'
  get '/student/:id' => 'student#destroy'
  get '/teacher/:id' => 'teacher#destroy'

  root 'home#home'
  resources :dashboard
  resources :students
  resources :courses 
  resources :teachers
  resources :users
  resources :login
  resources :sign_in

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    
end

app/models/course.rb
class Course < ApplicationRecord
       has_many :students
       
        @courses = Course.all
   
end

app/models/student.rb
class Student < ApplicationRecord
 
  
end

app/models/teacher.rb
class Teacher < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
        if current_user
            redirect_to '/dashboard'
        end
end

def about
end

def courses
end

def teachers
end

def students
end

def contact
end

end

app/controllers/login_controller.rb
class LoginController <Clearance::UsersController 
  
        $Users = User.all 
          
    
            def index
                @newUser= User.new
             
              end
    
            def create 
                User.create!(user_params)
            
                redirect_to '/dashboard'
            
            end
        
        def new
            User.new(
                    username: params[:username],
                    email: params[:email],
                    password: params[:password]
                    )
            end
              
                
            
        
        private
        def user_params 
            params.required(:user).permit( :username, :email, :password)
        end
    
    end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    $Users = User.all 
      
    

        def index
            @newUser= User.new
         
          end

        def create 
            User.create!(user_params)
        
            redirect_to '/dashboard'
        
        end
    
    def new
        User.new(
                username: params[:username],
                email: params[:email],
                password: params[:password]
                )
        end
          
            
        
    
    private
    def user_params 
        params.required(:user).permit( :username, :email, :password)
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/about/about.html.erb
<h1>Welcome to Astro Music School!</h1>
<p> A music school is an educational institution specialized in the study, training, and research of music. Such an institution can also be known as a school of music, music academy, music faculty, college of music, music department (of a larger institution), conservatory or conservatoire.</p>

#Course.create!(image: "http://ninebuzz.practicalmusicianblog.com/wp-content/uploads/2016/02/guitar-practice-mistakes.jpg", name: "Electric Guitar", session: "Fall 2019", teacher: "Tony Iommi", description: "A beginner friendly class focusing on blues, rock,punk, and metal concepts")


#Course.create!(image: "https://www.cmuse.org/wp-content/uploads/2018/04/Most-Difficult-Piano-Pieces.jpg", name: "Intro to Piano", session: "Fall 2019", teacher: "Mozart", description: "Learn Piano in 12 weeks with this beginner course.")

#form for login on navbar


# <%= form_for(@login) do |f| %>
# <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
#   aria-hidden="true">
#   <div class="modal-dialog" role="document">
#     <div class="modal-content">
#       <div class="modal-header text-center">
#         <li class="modal-title w-100 font-weight-bold">Login</l1>
#         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
#           <span aria-hidden="true">&times;</span>
#         </button>
#       </div>
#       <div class="modal-body mx-3">
#         <div class="md-form mb-5">
#           <i class="fas fa-envelope prefix grey-text"></i>
#           <label data-error="wrong" data-success="right" input="required" for="defaultForm-email">Email</label>
#           <input type="email" required id="defaultForm-email"  class="form-control validate">
          
#         </div>

#         <div class="md-form mb-4">
#           <i class="fas fa-lock prefix grey-text"></i>
#           <label data-error="wrong" data-success="right" input="required" for="defaultForm-pass">Password</label>
#           <input type="password" required id="defaultForm-pass" lass="form-control validate">
          
#         </div>

#       </div>
#       <div class="modal-footer d-flex justify-content-center">
#         <button class="btn btn-default">Login</button>
#       </div>
#     </div>
#   </div>
# </div>

# <div class="text-center">
#   <li style="float:right"><a href=""  method="POST" class="" data-toggle="modal" data-target="#modalLoginForm">Login</a></li>
# </div>
# <% end %>*/








# form for courses modal

# <img src="plus.png" type="button"  alt="Create a Course" width="5%" data-toggle="modal" id=" #myModal" data-target="#myModal">
# <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
#       aria-hidden="true">
#           <div class="modal fade">
#           <div class="modal-dialog" role="document">
#             <div class="modal-content">
#               <div class="modal-header">
#                 <h5 class="modal-title">Create A Course</h5>
#                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
#                   <span aria-hidden="true">×</span>
#                 </button>
#               </div>
#               <div class="modal-body">
                
# <%= form_for Course.new, url: courses_url do |f| %> 
                
#     <%= f.text_field :name, :required => true, :placeholder => 'Course Name' %>
#     <%= f.text_field :session, :required => true, :placeholder => 'Session' %>
#     <%= f.text_area :image, :cols => "50", :rows => "1" ,  :required => true, :placeholder => 'Choose an Image URL' %>
#     <%= f.text_field :teacher, :required => true, :placeholder => 'Teacher'%>
#     <%= f.text_area :description, :cols => "50", :rows => "10" , :required => true, :placeholder => 'Course Description'%>
#     <%= f.button :submit%>
#   <% end %>
#     </form>

#         </div>
#       </div>
#       <div class="modal-footer">
#         <button type="button" class="btn btn-primary">Save Course</button>
#         <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
#       </div>
#     </div>
#   </div>
# </div>

app/views/home/home.html.erb
<h1>Welcome to Astro Music School!</h1>


<h2  class="rightText"> Featured Music Classes</h2>
<h2> Featured Music History Courses</h2>



<div class="left" width="30%">
<div class="container">
<div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1" class=""></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2" class=""></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="3" class=""></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="4" class=""></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active carousel-item-left">
      <img src="joy.jpg" class="imgSize" alt="Joy Division"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
         

        </div>
      </div>
      <div class="carousel-item carousel-item-next carousel-item-left">
      <img src="eagles.jpg" class="imgSize" alt="The Eagles"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>


      <div class="carousel-item  carousel-item-left">
      <img src="sabbath.jpg" class="imgSize" alt="Black Sabbath"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
   

    <div class="centerCarousel carousel-item carousel-item-left">
      <img src="women.jpg" width="30%" alt="Women of Punk"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>Fourth slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>

      <div class="carousel-item ">
      <img src="tharpe.jpg" class="imgSize" alt="Sister Rosetta Tharpe"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>Fifth slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
     


      </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</div>
</div>




<div class="right" width="30%">
<div class="container">
<div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1" class=""></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2" class=""></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="3" class=""></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="4" class=""></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active carousel-item-left">
      <img src="electric.jpg" class="imgSize" alt="Electric Guitar"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
         

        </div>
      </div>
      <div class="carousel-item carousel-item-next carousel-item-left">
      <img src="piano.jpg" class="imgSize" alt="Piano Classes"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>


      <div class="carousel-item  carousel-item-left">
      <img src="violin.jpg" class="imgSize" alt="Violin Classes"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
   

    <div class="centerCarousel carousel-item carousel-item-left">
      <img src="classic.jpeg" class="imgSize" alt="Classical Guitar"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>Fourth slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>

      <div class="carousel-item ">
      <img src="sheet.jpg" class="imgSize" alt="Sheet Music Reading Comprehension"> 
        <div class="carousel-caption d-none d-md-block">
          <h5>Fifth slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
     


      </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</div>
</div>

<br>
<br> 
<br> 
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br> 
<br> 
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br> 
<br> 
<br>
<br>
<br>


<h1> Test</h1>
<p> Another test slkdjsldjklsdksldjlsdkssl skdncslkdnslkdncsdcsiodjsdcnsldcjsdlkscdl</p>

app/views/login/login.html.erb
<h1> Test</h1>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>