config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#home'
  get '/dashboard' => 'dashboard#dashboard'
  get '/login' => 'login#login'
  get '/signup' => 'signup#signup'
  # get '/courses' => 'courses#courses'
  get '/teachers' => 'teachers#teachers'
  get '/students' => 'students#students'
  get '/about' => 'about#about'
  get '/contact' => 'contact#contact'
  
 
  get '/course/:id' => 'courses#destroy'
  get '/student/:id' => 'student#destroy'
  get '/teacher/:id' => 'teacher#destroy'

  root 'home#home'
  resources :dashboard
  resources :students
  resources :courses 
  resources :teachers
  resources :users
  resources :login
  resources :sign_in

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    
end

app/models/course.rb
class Course < ApplicationRecord
       has_many :students
       
        @courses = Course.all
   
end

app/models/student.rb
class Student < ApplicationRecord
 
  
end

app/models/teacher.rb
class Teacher < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
        if current_user
            redirect_to '/dashboard'
        end
end

def about
end

def courses
end

def teachers
end

def students
end

def contact
end

end

app/controllers/login_controller.rb
class LoginController <Clearance::UsersController 
  
        $Users = User.all 
          
    
            def index
                @newUser= User.new
             
              end
    
            def create 
                User.create!(user_params)
            
                redirect_to '/dashboard'
            
            end
        
        def new
            User.new(
                    username: params[:username],
                    email: params[:email],
                    password: params[:password]
                    )
            end
              
                
            
        
        private
        def user_params 
            params.required(:user).permit( :username, :email, :password)
        end
    
    end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/_footer.html.erb
<footer>

<h1> Contact Us! </h1>

<p> Phone: 555.555.5555 Email: "email@gmail.com" </p>


</footer>

app/views/layouts/_header.html.erb
<h1 class="headerText"> Astro Music School </h1>

<img class="header" src="astro.jpg" alt="galaxy">

app/views/layouts/_nav.html.erb
<ul>

<li ><a href="/home">Home</a></li>
<li><a href="/about">About</a></li>
<li><a href="/courses">Courses</a></li>
<li><a href="/teachers">Meet Our Staff</a></li>
<li><a href="/students">Our Students</a></li>
<li><a href="/contact">Contact</a></li>
<li style="float:right">
    <%= form_tag("/search", method: "get") do %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
  <% end %></li>



<%= form_for User.new, url: dashboard_url do |f| %>
<div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <li style="float: right" class="modal-title w-100 font-weight-bold">Sign Up!</li>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="md-form mb-5">
          <i class="fas fa-user prefix grey-text"></i>
             <label data-error="wrong" data-success="right" input="required" for="orangeForm-name">Pick a Username</label>
            <input type="text" name="username" required id="orangeForm-name" class="form-control validate">
        </div>
        <div class="md-form mb-5">
          <i class="fas fa-envelope prefix grey-text"></i>
          <label data-error="wrong" data-success="right" input="required" for="orangeForm-email">Your email</label>
          <input type="email" name="email" required id="orangeForm-email"  class="form-control validate">
          
        </div>

        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          <label data-error="wrong" data-success="right" input="required" for="orangeForm-pass">Your password</label>
          <input type="password" name="password" required id="orangeForm-pass" class="form-control validate">
          
        </div>

      </div>
      <div class="modal-footer d-flex justify-content-center">
        <button class="btn btn-deep-orange">Sign up</button>
      </div>
    </div>
  </div>
</div>

<div class="text-center">
  <li style="float:right" ><a href="" class="" data-toggle="modal" data-target="#modalRegisterForm">Sign Up!</a></li>
</div>
<% end %>





<li>

  




  <%= form_for :session, url: sign_in_path do |form_builder| %>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <li style="float: right" class="modal-title w-100 font-weight-bold">Sign In</li>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <br>
            <br>
              <div class="loginModal">
              <i ></i>
              <%= render "sessions/form", form: form_builder %>
             
              <br>
              <br>
              <br>
            </div>
              </div>
    
              </div>
              
            </div>
          </div>
        </div>
    
    <div class="text-center">
      <li style="float:right" ><a href="/login" class="" data-toggle="modal" data-target="#myModal">Sign In</a></li>
    </div>
    <% end %>


</li>




</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Astro</title>
    <meta charset="UTF-8">
    <meta name="google" content="notranslate">
    <meta http-equiv="Content-Language" content="en">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Abel|Major+Mono+Display|Orbitron|Rajdhani" rel="stylesheet">
    
    <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
 

      <%= render "layouts/header" %>
        
      <br>
      <%= render "layouts/nav" %>
      <br>
      
        
        <%= yield %>
       
      <br>
     
      <%= render "layouts/footer" %>

 
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script>
  $( document ).ready(function(){
  $('#mycarousel').carousel();
  });
  $('#mycarousel').carousel({
  interval: 5 * 10
});


$(document).ready(function(){
  $("#myBtn").click(function(){
    $("#myModal").modal();
  });
});

</script>
  </body>
</html>